### Handling imbalanced dataset

Imbalance dataset will create a bias which will make it harder to model using ML

1. Up sampling
2. Down sampling

In [ ]:
import numpy as np 
import pandas as pd 

#set the random seed reproducibility
np.random.seed(123)

#create a dataframe with two classes
n_samples=1000
class_0_ratio=0.9 #multiplying this by samples (which will produce 900 data points)
n_class_0 = int(n_samples *class_0_ratio)
n_class_1 = n_samples-n_class_0# and remaining 100 will produced here

In [2]:
n_class_0,n_class_1

(900, 100)

In [3]:
#create my df with imbalance dataset

class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [6]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [9]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [ ]:
df['target'].value_counts() #checks the class distribution

target
0    900
1    100
Name: count, dtype: int64

### upsampling
It works by increasing the number of samples in the minority class, usually by duplicating rows or generating synthetic data (e.g., SMOTE).
This helps machine learning models learn equally from all classes.

In [11]:
### upsampling

df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [12]:
from sklearn.utils import resample
#the resample will try to extrapolate the minority

In [14]:
df_minority_upsampled=resample(df_minority,replace=True,#sample with replacement
        n_samples=len(df_majority),   
        random_state=42 #fixes seed
)

In [15]:
df_minority_upsampled.shape

(900, 3)

In [16]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [17]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [21]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### when to upsample

You should upsample when:

1. Your dataset is imbalanced and the minority class has very few samples.

2. You want the model to learn enough from the minority class to make accurate predictions.

3. You prefer to increase the dataset size (by duplicating or synthesizing samples) rather than remove majority-class data.

### Downsampling
Downsampling is a technique used to fix imbalanced datasets by reducing the number of samples in the majority class.
It does this by randomly removing rows from the overrepresented class.
This helps the model avoid bias toward the majority class.

In [22]:
import numpy as np 
import pandas as pd 

#set the random seed reproducibility
np.random.seed(123)

#create a dataframe with two classes
n_samples=1000
class_0_ratio=0.9 #multiplying this by samples (which will produce 900 data points)
n_class_0 = int(n_samples *class_0_ratio)
n_class_1 = n_samples-n_class_0# and remaining 100 will produced here

#create my df with imbalance dataset

class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

df1=pd.concat([class_0,class_1]).reset_index(drop=True)

df1['target'].value_counts() #checks the class distribution

target
0    900
1    100
Name: count, dtype: int64

In [ ]:
### downsampling

df_minority=df[df1['target']==1]
df_majority=df[df1['target']==0]

In [24]:
df_majority_downsampled=resample(df_majority,replace=False,#replace is false as we have to reduce the data points
        n_samples=len(df_minority),   
        random_state=42 #fixes seed
)

In [25]:
df_majority_downsampled.shape

(100, 3)

In [26]:
df_majority_downsampled.head

<bound method NDFrame.head of      feature_1  feature_2  target
70    0.468439   1.720920       0
827   1.089165  -0.464899       0
231   0.753869  -0.969798       0
588   0.588686  -0.704720       0
39    0.283627   1.012868       0
..         ...        ...     ...
398  -0.168426   0.553775       0
76   -0.403366   0.081491       0
196  -0.269293   0.611238       0
631  -0.295829   0.671673       0
751  -0.553404   0.804438       0

[100 rows x 3 columns]>

In [27]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [28]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64

### When to Downsample 

You should downsample when:

1. Your dataset is highly imbalanced, and the majority class has far more samples than the minority class.

2. You want to reduce bias in your model toward the majority class.

3. You prefer a smaller, faster-to-train dataset, and removing some majority samples won’t harm important patterns.